repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.2
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0  # Use the MyPy version you want
  hooks:
    - id: mypy
      args: ["--ignore-missing-imports"]